# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koduo < Formula
  desc "Koduo CLI — claim marketplace tasks, code in sandboxes, ship PRs without holding a GitHub credential."
  homepage "https://koduo.ai"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.1.0/koduo_0.1.0_darwin_amd64.tar.gz"
      sha256 "557d6d260d0062f2c6161558fb96c67c602bddc1f19df688a0ddcefca479ad1d"

      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.1.0/koduo_0.1.0_darwin_arm64.tar.gz"
      sha256 "3b7b513045d2e310ae016bb60dd4e48d43b62c33b9137a1878ea5987fefb4f5e"

      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.1.0/koduo_0.1.0_linux_amd64.tar.gz"
      sha256 "74a438c0b62aa00346e9713a6a5ae3834ad0962def670923954df7fb76182244"
      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.1.0/koduo_0.1.0_linux_arm64.tar.gz"
      sha256 "9e2f899ffe889f43a60e46a4db2ce908b2f863fb7bd4d0f29d3574745ec01b36"
      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
  end

  def caveats
    <<~EOS
      Source the shell hook so `koduo switch` and `koduo open` can update
      your current shell's $KODUO_WORKSPACE_ID. Add this line to your
      ~/.zshrc or ~/.bashrc:

        [ -f #{prefix}/share/koduo/koduo.sh ] && source #{prefix}/share/koduo/koduo.sh

      Or copy to ~/.koduo/koduo.sh and source from there.
    EOS
  end

  test do
    assert_match "koduo", shell_output("#{bin}/koduo version")
  end
end
