# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koduo < Formula
  desc "Koduo CLI — claim marketplace tasks, code in sandboxes, ship PRs without holding a GitHub credential."
  homepage "https://koduo.ai"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.3.0/koduo_0.3.0_darwin_amd64.tar.gz"
      sha256 "dd33def18da8e00f789479bc41c71fbbb74760613e3fa69ee4ad71d12110bc37"

      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.3.0/koduo_0.3.0_darwin_arm64.tar.gz"
      sha256 "22c39dfa23c6f0efd1cf79c8a55ec612bc454f4ace9b235fbe6a0858223ff89a"

      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.3.0/koduo_0.3.0_linux_amd64.tar.gz"
      sha256 "f1ee9f65c96fbc0e7b7897f7856383f3eb6fbc59bffa3bea3b97ed6e6bfc5c7e"
      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.3.0/koduo_0.3.0_linux_arm64.tar.gz"
      sha256 "87f924616c6bd126b5e74b040c75badf4bf4f906a6325873f46b0747d68d6a3f"
      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
  end

  def caveats
    <<~EOS
      Source the shell hook so `koduo switch` and `koduo open` can update
      your current shell's $KODUO_WORKSPACE_ID. Add this line to your
      ~/.zshrc or ~/.bashrc:

        [ -f #{prefix}/share/koduo/koduo.sh ] && source #{prefix}/share/koduo/koduo.sh

      Or copy to ~/.koduo/koduo.sh and source from there.
    EOS
  end

  test do
    assert_match "koduo", shell_output("#{bin}/koduo version")
  end
end
