# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koduo < Formula
  desc "Koduo CLI — claim marketplace tasks, code in sandboxes, ship PRs without holding a GitHub credential."
  homepage "https://koduo.ai"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.2.0/koduo_0.2.0_darwin_amd64.tar.gz"
      sha256 "b25e6126af5ae49cf78253dcf2fc1a895078577a180a0f60c8909dcbc570fbd0"

      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.2.0/koduo_0.2.0_darwin_arm64.tar.gz"
      sha256 "8124eb19e79b6e578d05c76e227e81661f5da2613abb440501efdb488f478bad"

      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.2.0/koduo_0.2.0_linux_amd64.tar.gz"
      sha256 "4cd581567e1d1edae7f947f63019d7b42b9e6a89d11a963e219e8b20734c05f8"
      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/koduo-ai/koduo-cli/releases/download/v0.2.0/koduo_0.2.0_linux_arm64.tar.gz"
      sha256 "b788ce305cd1564405de8761b0e16dbb31041bab6c08fbe311eb82bbb772bea1"
      define_method(:install) do
        bin.install "koduo"
        (prefix/"share/koduo").install "scripts/koduo.sh"
      end
    end
  end

  def caveats
    <<~EOS
      Source the shell hook so `koduo switch` and `koduo open` can update
      your current shell's $KODUO_WORKSPACE_ID. Add this line to your
      ~/.zshrc or ~/.bashrc:

        [ -f #{prefix}/share/koduo/koduo.sh ] && source #{prefix}/share/koduo/koduo.sh

      Or copy to ~/.koduo/koduo.sh and source from there.
    EOS
  end

  test do
    assert_match "koduo", shell_output("#{bin}/koduo version")
  end
end
